### ISSUE TITLE
[Feature Request] MQTT Auto Discovery

### ISSUE THREAD

**Issue by atxbyea** [logichousepcb/Wemos32#1]
Should we try to get MQTT discovery working in HA ? I've started looking at this and it looks pretty straight forward, I just need some time to play around with it.

https://github.com/plapointe6/HAMqttDevice

**Comment by logichousepcb** [comment]
Yes. I have to read up on how it works. It might be a better option to control and receive data.

**Comment by logichousepcb** [comment]
I have it figured out.  Now I just need to implement it.  I'm finishing up the function and it will be active for version 1.7 with a couple additional config variables in the config file.  the HA discovery topic and a function to turn it on or off.

**Comment by logichousepcb** [comment]
MQTT auto discovery now works for binary sensor output and temperature for the on board DS1B20.  Input on the plate for version 1.7 to control relays.

**Comment by logichousepcb** [comment]
Auto discovery added with option to turn off in settings
